function doGet() {
  return HtmlService.createTemplateFromFile('Index').evaluate().setTitle('Teniski turnir').addMetaTag('viewport','width=device-width, initial-scale=1');
}
function include_(name) { return HtmlService.createHtmlOutputFromFile(name).getContent(); }
function properties_() {return PropertiesService.getScriptProperties();}
function uid_(){return Utilities.getUuid();}
function database_(){var id=properties_().getProperty('SPREADSHEET_ID');if(!id)throw new Error('Baza još nije povezana.');return SpreadsheetApp.openById(id);}
function lock_(fn){var l=LockService.getScriptLock();if(!l.tryLock(20000))throw new Error('Sistem je zauzet. Pokušajte ponovo.');try{return fn();}finally{l.releaseLock();}}
function assertOrganizer_(){
  var active=SpreadsheetApp.getActiveSpreadsheet(),mail=Session.getActiveUser().getEmail(),allowed=JSON.parse(properties_().getProperty('ORGANIZATORI')||'[]');
  if(!active||active.getId()!==properties_().getProperty('SPREADSHEET_ID')||!mail||allowed.indexOf(mail.toLowerCase())<0)throw new Error('Nemate ovlašćenje za organizatorsku radnju.');
}
function read_(ss){var db={};Object.keys(SCHEMA).forEach(function(name){var sh=ss.getSheetByName(name);if(!sh)throw new Error('Nedostaje list '+name);if(sh.getLastRow()>10000)throw new Error('Baza je prevelika za ovu verziju.');var values=sh.getDataRange().getValues(),headers=SCHEMA[name].map(function(c){return c[0];});if(headers.join('|')!==values[0].join('|'))throw new Error('Promijenjena struktura lista '+name);db[name]=values.slice(1).filter(function(row){return row[0]!=='';}).map(function(row){var r={};headers.forEach(function(h,i){r[h]=row[i] instanceof Date?row[i].toISOString():row[i];});return r;});});return db;}
function writeTables_(ss,db,names){names.forEach(function(name){var sh=ss.getSheetByName(name),headers=SCHEMA[name].map(function(c){return c[0];});var old=Math.max(sh.getLastRow()-1,0),rows=db[name].map(function(row){return headers.map(function(h){return Engine.safeCell(row[h]==null?'':row[h]);});});var count=Math.max(old,rows.length);if(count){while(rows.length<count)rows.push(headers.map(function(){return '';}));if(sh.getMaxRows()<count+1)sh.insertRowsAfter(sh.getMaxRows(),count+1-sh.getMaxRows());sh.getRange(2,1,count,headers.length).setValues(rows);}});SpreadsheetApp.flush();}
/* Write-ahead recovery: no partially written state is served. Journal is private. */
function recover_(ss){var j=ss.getSheetByName('_Transakcija');if(j&&j.getRange('A1').getValue()==='PENDING'){var chunks=j.getRange(2,1,j.getLastRow()-1,1).getValues().map(function(r){if(String(r[0])[0]!=='J')throw new Error('Neispravan dnevnik oporavka.');return String(r[0]).slice(1);}).join(''),backup=JSON.parse(chunks);writeTables_(ss,backup,Object.keys(backup));j.getRange('A1').setValue('RECOVERED');SpreadsheetApp.flush();CacheService.getScriptCache().remove('public-v1');}}
function save_(ss,before,after,names){var j=ss.getSheetByName('_Transakcija'),snapshot={};names.forEach(function(n){snapshot[n]=before[n];});var data=JSON.stringify(snapshot),chunks=data.match(/[\s\S]{1,40000}/g)||['{}'];j.clearContents();j.getRange(2,1,chunks.length,1).setValues(chunks.map(function(c){return['J'+c];}));SpreadsheetApp.flush();j.getRange('A1').setValue('PENDING');SpreadsheetApp.flush();try{writeTables_(ss,after,names);j.getRange('A1').setValue('COMMITTED');SpreadsheetApp.flush();j.clearContents();CacheService.getScriptCache().remove('public-v1');}catch(e){recover_(ss);throw e;}}
function mutate_(names,fn){assertOrganizer_();return lock_(function(){var ss=database_();recover_(ss);var before=read_(ss),after=JSON.parse(JSON.stringify(before));var result=fn(after);save_(ss,before,after,names);return result;});}
function getPublicData(){
  try{return lock_(function(){var ss=database_();recover_(ss);var cache=CacheService.getScriptCache(),hit=cache.get('public-v1');if(hit)return JSON.parse(hit);var data=Engine.publicData(read_(ss),Date.now()),serialized=JSON.stringify(data);if(Utilities.newBlob(serialized).getBytes().length<95000)cache.put('public-v1',serialized,25);return data;});}
  catch(e){throw new Error('Podaci trenutno nisu dostupni. Pokušajte ponovo kasnije.');}
}
function digest_(text){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,text,Utilities.Charset.UTF_8).map(function(b){return('0'+((b+256)%256).toString(16)).slice(-2);}).join('');}
function getRegistrationChallenge(){return lock_(function(){var cache=CacheService.getScriptCache(),key='challenge-minute-'+Math.floor(Date.now()/60000),count=+(cache.get(key)||0);if(count>=120)throw new Error('Previše zahtjeva. Pokušajte za minut.');cache.put(key,String(count+1),70);var token=uid_();cache.put('challenge-'+token,String(Date.now()),900);return {token:token,expiresIn:900};});}
function submitRegistration(input){
  if(!input||typeof input!=='object'||JSON.stringify(input).length>5000)throw new Error('Neispravan zahtjev.');
  return lock_(function(){
    var ss=database_();recover_(ss);var before=read_(ss),key=String(input.zahtjev_id||'');if(!/^[a-zA-Z0-9-]{20,80}$/.test(key))throw new Error('Osvježite obrazac i pokušajte ponovo.');
    var fields=['ime_prezime','email','telefon','kategorija_id','klub_grad','napomena','saglasnost','verzija_pravila'],fingerprint=digest_(JSON.stringify(fields.map(function(f){return input[f];}))),prior=before.Prijave.find(function(p){return p.zahtjev_id===key;});
    if(prior){if(prior.otisak!==fingerprint)throw new Error('Zahtjev je već iskorišćen sa drugim podacima.');return {ok:true,id:prior.id,status:prior.status};}
    var cache=CacheService.getScriptCache(),issued=Number(cache.get('challenge-'+String(input.token||''))),now=Date.now();
    if(input.website || !issued || now-issued<2500 || now-issued>900000)throw new Error('Provjera obrasca je istekla. Osvježite provjeru i pokušajte ponovo nakon nekoliko sekundi.');
    var minute='submit-minute-'+Math.floor(now/60000),count=Number(cache.get(minute)||0);if(count>=30)throw new Error('Veliki broj prijava. Pokušajte za minut.');cache.put(minute,String(count+1),70);
    var row=Engine.validateRegistration(before,input,now);row.id=uid_();row.zahtjev_id=key;row.otisak=fingerprint;row.vrijeme_prijave=new Date(now).toISOString();row.demo=Engine.yes(before.Turnir[0].demo);
    var after=JSON.parse(JSON.stringify(before));after.Prijave.push(row);save_(ss,before,after,['Prijave']);cache.remove('challenge-'+input.token);return {ok:true,id:row.id,status:row.status};
  });
}
function onOpen(){var ss=SpreadsheetApp.getActiveSpreadsheet();if(!ss)return;SpreadsheetApp.getUi().createMenu('Tenis').addItem('Inicijalno podešavanje','initialize_').addSeparator().addItem('Dodaj kategoriju','addCategory_').addItem('Dodaj teren','addCourt_').addItem('Dodaj obavještenje','addNotice_').addSeparator().addItem('Status odabrane prijave','approveSelected_').addItem('Javno ime / klub / nosilac','editParticipant_').addItem('Generiši žrijeb odabrane kategorije','drawSelected_').addItem('Objavi žrijeb odabrane kategorije','publishDraw_').addSeparator().addItem('Termin / status odabranog meča','scheduleSelected_').addItem('Rezultat odabranog meča','resultSelected_').addItem('Poništi rezultat odabranog meča','resetSelected_').addItem('Provjeri raspored','checkSchedule_').addItem('Izvezi učesnike (CSV)','exportParticipants_').addSeparator().addItem('Učitaj DEMO u praznu bazu','loadDemo_').addItem('Ukloni DEMO podatke','removeDemo_').addToUi();}
function initialize_(){
  var ss=SpreadsheetApp.getActiveSpreadsheet(),email=Session.getActiveUser().getEmail();if(!ss||!email)throw new Error('Pokrenite iz Apps Script projekta vezanog za vašu tabelu.');
  if(properties_().getProperty('SPREADSHEET_ID'))assertOrganizer_();
  lock_(function(){
    Object.keys(SCHEMA).forEach(function(name){var sh=ss.getSheetByName(name);if(sh&&sh.getLastRow()>0&&sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].join('|')!==SCHEMA[name].map(function(c){return c[0];}).join('|'))throw new Error('Postojeći list '+name+' ima drugu strukturu. Koristite praznu tabelu.');});
    properties_().setProperty('SPREADSHEET_ID',ss.getId());if(!properties_().getProperty('ORGANIZATORI'))properties_().setProperty('ORGANIZATORI',JSON.stringify([email.toLowerCase()]));
    Object.keys(SCHEMA).forEach(function(name){
      var sh=ss.getSheetByName(name)||ss.insertSheet(name),columns=SCHEMA[name];if(sh.getMaxColumns()<columns.length)sh.insertColumnsAfter(sh.getMaxColumns(),columns.length-sh.getMaxColumns());
      sh.getRange(1,1,1,columns.length).setValues([columns.map(function(c){return c[0];})]).setBackground('#123f32').setFontColor('#ffffff').setFontWeight('bold');sh.setFrozenRows(1);sh.setRowHeight(1,36);
      columns.forEach(function(c,i){sh.setColumnWidth(i+1,c[1]==='tekst'?220:170);sh.getRange(1,i+1).setNote(c[1]+' | '+(c[2]?'Obavezno':'Opciono')+' | '+c[3]+'\n'+String(c[5])+'\nPrimjer: '+c[4]);var range=sh.getRange(2,i+1,sh.getMaxRows()-1,1);if(['ID','tekst','datum','datum-vrijeme'].indexOf(c[1])>=0)range.setNumberFormat('@');if(Array.isArray(c[5]))range.setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList(c[5],true).setAllowInvalid(false).build());if(c[1]==='boolean')range.setDataValidation(SpreadsheetApp.newDataValidation().requireCheckbox().setAllowInvalid(false).build());if(c[1]==='broj'){var bounds={limit_ucesnika:[2,256],setovi_za_pobjedu:[1,3],gemovi_u_setu:[1,12],tajbrejk_na:[1,12],tajbrejk_poeni:[5,15],trajanje_min:[15,600],prioritet:[1,3],kotizacija:[0,100000]};if(bounds[c[0]])range.setDataValidation(SpreadsheetApp.newDataValidation().requireNumberBetween(bounds[c[0]][0],bounds[c[0]][1]).setAllowInvalid(false).build());}
      });
      var existing=sh.getProtections(SpreadsheetApp.ProtectionType.SHEET).find(function(p){return p.getDescription()==='TENIS_SYSTEM';}),protection=existing||sh.protect().setDescription('TENIS_SYSTEM');protection.setWarningOnly(false);protection.addEditor(email);protection.getEditors().forEach(function(u){if(u.getEmail()!==email)protection.removeEditor(u);});if(protection.canDomainEdit())protection.setDomainEdit(false);protection.setUnprotectedRanges(columns.map(function(c,i){return c[3]==='ručno'?sh.getRange(2,i+1,sh.getMaxRows()-1,1):null;}).filter(Boolean));
    });
    var journal=ss.getSheetByName('_Transakcija')||ss.insertSheet('_Transakcija');journal.hideSheet();if(!journal.getProtections(SpreadsheetApp.ProtectionType.SHEET).length){var p=journal.protect().setDescription('TENIS_SYSTEM');p.addEditor(email);p.getEditors().forEach(function(u){if(u.getEmail()!==email)p.removeEditor(u);});if(p.canDomainEdit())p.setDomainEdit(false);}
    if(ss.getSheetByName('Turnir').getLastRow()<2)writeTables_(ss,{Turnir:[{id:'TURNIR',naziv:'Naziv turnira nije podešen',status_prijava:'Zatvorene',verzija_pravila:'1',demo:false}]},['Turnir']);
    var triggers=ScriptApp.getProjectTriggers();if(!triggers.some(function(t){return t.getHandlerFunction()==='edited_';}))ScriptApp.newTrigger('edited_').forSpreadsheet(ss).onEdit().create();
    CacheService.getScriptCache().remove('public-v1');
  });onOpen();SpreadsheetApp.getUi().alert('Baza je spremna. Popunite Turnir, dodajte kategorije i terene kroz meni. Prijave ostaju zatvorene do unosa pravila i roka.');
}
function edited_(e){if(e&&e.source&&e.source.getId()===properties_().getProperty('SPREADSHEET_ID'))CacheService.getScriptCache().remove('public-v1');}
function prompt_(title,help){var ui=SpreadsheetApp.getUi(),r=ui.prompt(title,help,ui.ButtonSet.OK_CANCEL);return r.getSelectedButton()===ui.Button.OK?r.getResponseText().trim():null;}
function selected_(sheet){assertOrganizer_();var sh=SpreadsheetApp.getActiveSheet();if(sh.getName()!==sheet||sh.getActiveRange().getRow()<2)throw new Error('Odaberite red u listu '+sheet+'.');return String(sh.getRange(sh.getActiveRange().getRow(),1).getValue());}
function addCategory_(){var name=prompt_('Nova kategorija','Naziv kategorije');if(!name)return;mutate_(['Kategorije'],function(db){if(db.Kategorije.length>=32)throw new Error('Najviše 32 kategorije.');db.Kategorije.push({id:uid_(),naziv:name,format:'Singl eliminacija',limit_ucesnika:32,kotizacija:0,valuta:'KM',aktivna:false,lista_cekanja:false,setovi_za_pobjedu:2,gemovi_u_setu:6,tajbrejk_na:6,tajbrejk_poeni:7,trajanje_min:90,pravila:'',demo:false});});}
function addCourt_(){var name=prompt_('Novi teren','Naziv terena');if(!name)return;mutate_(['Tereni'],function(db){db.Tereni.push({id:uid_(),naziv:name,aktivan:false,demo:false});});}
function addNotice_(){var title=prompt_('Novo obavještenje','Naslov');if(!title)return;mutate_(['Obavjestenja'],function(db){db.Obavjestenja.push({id:uid_(),naslov:title,tekst:'',datum:new Date().toISOString(),prioritet:1,status:'Nacrt',demo:false});});}
function approveSelected_(){var id=selected_('Prijave'),s=prompt_('Status prijave','Odobrena / Odbijena / Lista čekanja / Na čekanju');if(s===null)return;mutate_(['Prijave','Ucesnici'],function(db){Engine.approve(db,id,s,uid_);});}
function editParticipant_(){var id=selected_('Ucesnici'),v=prompt_('Javni podaci učesnika','Javno ime | klub ili grad | broj nosioca (prazno za nenosioca)');if(v===null)return;var parts=v.split('|').map(function(x){return x.trim();});mutate_(['Ucesnici'],function(db){var p=db.Ucesnici.find(function(x){return x.id===id;});if(!p||!parts[0]||parts[0].length>100||(parts[1]||'').length>100)throw new Error('Provjerite unos.');if(db.Zrijeb.some(function(z){return z.kategorija_id===p.kategorija_id;}))throw new Error('Nosioci i sastav su zaključani nakon generisanja žrijeba.');p.javno_ime=parts[0];p.klub_grad=parts[1]||'';p.nosilac=parts[2]?Engine.integer(parts[2],1,256,'Nosilac'):'';});}
function drawSelected_(){var id=selected_('Kategorije');mutate_(['Zrijeb','Mecevi'],function(db){Engine.generateDraw(db,id,uid_,Math.random);});SpreadsheetApp.getUi().alert('Žrijeb je sačuvan kao nacrt. Provjerite ga i objavite kroz meni. Sastav kategorije je zaključan.');}
function publishDraw_(){var id=selected_('Kategorije');mutate_(['Zrijeb'],function(db){var rows=db.Zrijeb.filter(function(z){return z.kategorija_id===id;});if(!rows.length)throw new Error('Prvo generišite žrijeb.');rows.forEach(function(z){z.objavljen=true;});});}
function scheduleSelected_(){var id=selected_('Mecevi'),v=prompt_('Termin i status','ISO termin sa zonom | teren ID | trajanje u minutama | status. Primjer formata: 2027-06-10T10:00:00+02:00 | ID | 90 | Zakazan');if(v===null)return;var p=v.split('|').map(function(s){return s.trim();});mutate_(['Mecevi'],function(db){Engine.schedule(db,id,p[0]||'',p[1]||'',p[2],p[3]);});}
function resultSelected_(){var id=selected_('Mecevi'),v=prompt_('Rezultat','Pobjednik 1 ili 2 | Regularno / Predaja / Bez igre | setovi. Primjer: 1 | Regularno | 6-4 7-6(7-5)');if(v===null)return;var p=v.split('|').map(function(s){return s.trim();});mutate_(['Mecevi'],function(db){var m=db.Mecevi.find(function(x){return x.id===id;});if(!m||!['1','2'].includes(p[0]))throw new Error('Pobjednik mora biti 1 ili 2.');Engine.result(db,id,p[2]||'',p[1],m['igrac'+p[0]+'_id']);});}
function resetSelected_(){var id=selected_('Mecevi'),v=prompt_('Poništavanje rezultata','Upišite PONIŠTI. Time uklanjate rezultat i oslobađate mjesto u sljedećoj rundi; termine zavisnih mečeva treba ponovo zakazati.');if(v!=='PONIŠTI')return;mutate_(['Mecevi'],function(db){Engine.resetResult(db,id);});}
function checkSchedule_(){assertOrganizer_();var errors=lock_(function(){var ss=database_();recover_(ss);return Engine.conflicts(read_(ss));});SpreadsheetApp.getUi().alert(errors.length?errors.join('\n'):'Nema konflikata prema upisanim terminima i procijenjenom trajanju.');}
function exportParticipants_(){assertOrganizer_();var data=lock_(function(){var ss=database_();recover_(ss);return Engine.publicData(read_(ss),Date.now());}),rows=[['Javno ime','Kategorija','Klub ili grad']].concat(data.ucesnici.map(function(p){return[p.javno_ime,(data.kategorije.find(function(c){return c.id===p.kategorija_id;})||{}).naziv||p.kategorija_id,p.klub_grad];})),csv='\uFEFF'+rows.map(function(row){return row.map(function(v){return '"'+String(Engine.safeCell(v||'')).replace(/"/g,'""')+'"';}).join(';');}).join('\r\n'),url='data:text/csv;charset=utf-8,'+encodeURIComponent(csv);SpreadsheetApp.getUi().showModalDialog(HtmlService.createHtmlOutput('<p>Izvoz sadrži samo javne podatke.</p><a download="ucesnici.csv" href="'+url+'">Preuzmi CSV</a>'),'Izvoz učesnika');}

