var Demo = { create: function(now,uid) {
  var db={};Object.keys(SCHEMA).forEach(function(n){db[n]=[];});
  var day=new Date(now);day.setUTCHours(8,0,0,0);var later=new Date(now+14*86400000).toISOString();
  db.Turnir=[{id:'DEMO-TURNIR',naziv:'DEMO · Teniski turnir',opis:'Prijave, žrijeb i rezultati na jednom mjestu. Ovo je probni turnir za upoznavanje sa aplikacijom.',lokacija:'DEMO · Lokacija turnira',datum_od:day.toISOString().slice(0,10),datum_do:new Date(now+2*86400000).toISOString().slice(0,10),rok_prijave:later,status_prijava:'Otvorene',kontakt_javni:'DEMO · Unesite javni kontakt organizatora.',pravila:'DEMO PRAVILA — isključivo za testiranje.\nSingl, eliminacioni sistem. Meč se igra na dva dobijena seta. Taj-brejk na 6:6 do sedam poena, uz dva razlike.\nStvarna pravila određuje organizator prije otvaranja prijava.',obrada_podataka:'DEMO OBAVJEŠTENJE — nije namijenjeno stvarnim prijavama. Koristite isključivo izmišljene podatke.\nU stvarnom turniru kontakt podatke vidi organizator. Javno se prikazuju odobreno ime, kategorija i uneseni klub ili grad. Organizator prije objave dopunjava svrhu i rok čuvanja podataka, svoj identitet i kontakt za zahtjeve.',verzija_pravila:'DEMO-1',demo:true}];
  db.Kategorije=[{id:'DEMO-C1',naziv:'DEMO · Singl A',format:'Singl eliminacija',limit_ucesnika:16,kotizacija:0,valuta:'KM',aktivna:true,lista_cekanja:false,setovi_za_pobjedu:2,gemovi_u_setu:6,tajbrejk_na:6,tajbrejk_poeni:7,trajanje_min:90,pravila:'DEMO · Pojedinačna konkurencija.',demo:true},{id:'DEMO-C2',naziv:'DEMO · Singl B',format:'Singl eliminacija',limit_ucesnika:8,kotizacija:0,valuta:'KM',aktivna:true,lista_cekanja:true,setovi_za_pobjedu:2,gemovi_u_setu:6,tajbrejk_na:6,tajbrejk_poeni:7,trajanje_min:90,pravila:'DEMO · Otvorena za probne prijave.',demo:true}];
  db.Tereni=[{id:'DEMO-T1',naziv:'DEMO · Teren 1',lokacija:'DEMO',aktivan:true,demo:true},{id:'DEMO-T2',naziv:'DEMO · Teren 2',lokacija:'DEMO',aktivan:true,demo:true}];
  for(var i=1;i<=6;i++){var id='DEMO-P'+i;db.Prijave.push({id:id,zahtjev_id:uid(),ime_prezime:'DEMO Igrač '+i,email:'demo'+i+'@example.invalid',telefon:'+3876000000'+i,kategorija_id:'DEMO-C1',klub_grad:'DEMO Klub '+(i%2+1),napomena:'DEMO privatna napomena',vrijeme_prijave:new Date(now).toISOString(),status:'Odobrena',verzija_pravila:'DEMO-1',demo:true});db.Ucesnici.push({id:'DEMO-U'+i,prijava_id:id,javno_ime:'DEMO Igrač '+i,kategorija_id:'DEMO-C1',klub_grad:'DEMO Klub '+(i%2+1),nosilac:i<=2?i:'',status:'Aktivan',demo:true});}
  Engine.generateDraw(db,'DEMO-C1',uid,function(){return .42;});db.Zrijeb.forEach(function(z){z.objavljen=true;});
  var played=db.Mecevi.find(function(m){return m.runda===1&&!m.ishod;});Engine.result(db,played.id,'6-4 7-6(7-5)','Regularno',played.igrac1_id);
  db.Mecevi.filter(function(m){return m.igrac1_id&&m.igrac2_id&&!m.ishod;}).forEach(function(m,i){m.pocetak=new Date(day.getTime()+(i+2)*90*60000).toISOString();m.teren_id='DEMO-T'+(i%2+1);});
  db.Obavjestenja=[{id:'DEMO-N1',naslov:'DEMO · Dobro došli na turnir',tekst:'Ovaj prikaz služi za testiranje. Stvarne datume, pravila i podatke o turniru podešavate u Google Sheets.',datum:new Date(now).toISOString(),prioritet:2,status:'Objavljeno',demo:true}];return db;
}};
function loadDemo_(){mutate_(Object.keys(SCHEMA),function(db){if(Object.keys(db).some(function(n){return n!=='Turnir'&&db[n].length;}))throw new Error('DEMO se učitava samo u praznu bazu.');var d=Demo.create(Date.now(),uid_);Object.keys(d).forEach(function(n){db[n]=d[n];});});}
function removeDemo_(){var choice=prompt_('Uklanjanje DEMO podataka','Upišite UKLONI DEMO. Struktura ostaje. Prvo provjerite da nema stvarnih prijava vezanih za DEMO kategorije.');if(choice!=='UKLONI DEMO')return;mutate_(Object.keys(SCHEMA),function(db){var cats=db.Kategorije.filter(function(c){return Engine.yes(c.demo);}).map(function(c){return c.id;});if(db.Prijave.some(function(p){return !Engine.yes(p.demo)&&cats.includes(p.kategorija_id);}))throw new Error('Postoje nedemonstracione prijave u DEMO kategoriji. Napravite novu praznu tabelu za stvarni turnir.');Object.keys(db).forEach(function(n){db[n]=db[n].filter(function(r){return !Engine.yes(r.demo);});});if(!db.Turnir.length)db.Turnir=[{id:'TURNIR',naziv:'Naziv turnira nije podešen',status_prijava:'Zatvorene',verzija_pravila:'1',demo:false}];});}
