/* Column definition: name, type, required, owner, example, validation / reference. */
var SCHEMA = {
 Turnir: [
 ['id','ID',true,'sistem','TURNIR','Jedan red'],['naziv','tekst',true,'ručno','Naziv turnira','Do 160 znakova'],['opis','tekst',false,'ručno','','Opis'],['lokacija','tekst',false,'ručno','','Javna lokacija'],['datum_od','datum',false,'ručno','2027-06-10','ISO YYYY-MM-DD'],['datum_do','datum',false,'ručno','2027-06-12','ISO YYYY-MM-DD'],['rok_prijave','datum-vrijeme',true,'ručno','2027-06-09T20:00:00+02:00','ISO sa vremenskom zonom'],['status_prijava','izbor',true,'ručno','Zatvorene',['Zatvorene','Otvorene']],['kontakt_javni','tekst',false,'ručno','','Samo kontakt namijenjen objavi'],['pravila','tekst',true,'ručno','','Obavezno prije otvaranja prijava'],['obrada_podataka','tekst',true,'ručno','','Organizator, svrha, podaci, javna polja, rok čuvanja i kontakt za zahtjeve'],['verzija_pravila','tekst',true,'ručno','1','Promijeniti nakon izmjene pravila ili obavještenja'],['demo','boolean',true,'sistem',false,'DEMO oznaka']],
 Kategorije: [
 ['id','ID',true,'sistem','CAT-uuid','Prijave/Ucesnici/Zrijeb/Mecevi.kategorija_id'],['naziv','tekst',true,'ručno','Singl','Naziv kategorije'],['format','izbor',true,'ručno','Singl eliminacija',['Singl eliminacija']],['limit_ucesnika','broj',true,'ručno',32,'Cijeli broj 2–256'],['kotizacija','broj',true,'ručno',0,'Broj >= 0; 0 bez kotizacije'],['valuta','tekst',true,'ručno','KM','Oznaka valute'],['aktivna','boolean',true,'ručno',false,'TRUE/FALSE'],['lista_cekanja','boolean',true,'ručno',false,'TRUE/FALSE'],['setovi_za_pobjedu','broj',true,'ručno',2,'1–3'],['gemovi_u_setu','broj',true,'ručno',6,'1–12'],['tajbrejk_na','broj',true,'ručno',6,'Mora biti jednako gemovi_u_setu u v1'],['tajbrejk_poeni','broj',true,'ručno',7,'5–15; razlika dva'],['trajanje_min','broj',true,'ručno',90,'15–600'],['pravila','tekst',false,'ručno','','Dodatna pravila; bez superseta ili odlučujućeg match taj-brejka u v1'],['demo','boolean',true,'sistem',false,'DEMO oznaka']],
 Prijave: [
 ['id','ID',true,'sistem','uuid','Ucesnici.prijava_id'],['zahtjev_id','ID',true,'sistem','uuid','Jedinstven ključ ponovljenog zahtjeva'],['otisak','tekst',true,'sistem','SHA-256','Provjera istog sadržaja pri ponovljenom zahtjevu'],['ime_prezime','tekst',true,'sistem','DEMO Igrač 1','Do 100 znakova; privatno do odobrenja'],['email','tekst',true,'sistem','demo@example.invalid','Privatno; normalizovano'],['telefon','tekst',true,'sistem','+38760000001','Privatno; 7–15 cifara'],['kategorija_id','ID',true,'sistem','CAT-uuid','Kategorije.id'],['klub_grad','tekst',false,'sistem','','Javno nakon odobrenja'],['napomena','tekst',false,'sistem','','Privatno; do 1000 znakova'],['vrijeme_prijave','datum-vrijeme',true,'sistem','','ISO UTC'],['status','izbor',true,'meni','Na čekanju',['Na čekanju','Odobrena','Odbijena','Lista čekanja']],['verzija_pravila','tekst',true,'sistem','1','Verzija prihvaćenog teksta'],['demo','boolean',true,'sistem',false,'DEMO oznaka']],
 Ucesnici: [
 ['id','ID',true,'sistem','uuid','Zrijeb.ucesnik_id; Mecevi.igrac1_id/igrac2_id/pobjednik_id'],['prijava_id','ID',true,'sistem','uuid','Prijave.id; nije javno'],['javno_ime','tekst',true,'meni','DEMO Igrač 1','Do 100 znakova'],['kategorija_id','ID',true,'sistem','CAT-uuid','Kategorije.id'],['klub_grad','tekst',false,'meni','','Javno; do 100 znakova'],['nosilac','broj',false,'meni',1,'Uzastopni brojevi 1..N; bez duplikata'],['status','izbor',true,'meni','Aktivan',['Aktivan','Povučen']],['demo','boolean',true,'sistem',false,'DEMO oznaka']],
 Tereni: [
 ['id','ID',true,'sistem','uuid','Mecevi.teren_id'],['naziv','tekst',true,'ručno','Teren 1','Naziv'],['lokacija','tekst',false,'ručno','','Lokacija'],['aktivan','boolean',true,'ručno',false,'TRUE/FALSE'],['dostupan_od','datum-vrijeme',false,'ručno','','ISO sa vremenskom zonom; prazno bez donje granice'],['dostupan_do','datum-vrijeme',false,'ručno','','ISO sa vremenskom zonom; prazno bez gornje granice'],['demo','boolean',true,'sistem',false,'DEMO oznaka']],
 Zrijeb: [
 ['id','ID',true,'sistem','uuid','ID pozicije'],['zrijeb_id','ID',true,'sistem','uuid','Mecevi.zrijeb_id'],['kategorija_id','ID',true,'sistem','CAT-uuid','Kategorije.id'],['pozicija','broj',true,'sistem',1,'Jedinstvena u žrijebu'],['ucesnik_id','ID',false,'sistem','uuid','Ucesnici.id; prazno BYE'],['nosilac','broj',false,'sistem',1,'Snimak nosioca pri žrijebu'],['slobodan_prolaz','boolean',true,'sistem',false,'Prazna pozicija'],['objavljen','boolean',true,'meni',false,'Meni objavljuje cijeli žrijeb'],['demo','boolean',true,'sistem',false,'DEMO oznaka']],
 Mecevi: [
 ['id','ID',true,'sistem','uuid','Veze narednih rundi'],['zrijeb_id','ID',true,'sistem','uuid','Zrijeb.zrijeb_id'],['kategorija_id','ID',true,'sistem','CAT-uuid','Kategorije.id'],['runda','broj',true,'sistem',1,'1 je prva runda'],['pozicija','broj',true,'sistem',1,'Pozicija unutar runde'],['igrac1_id','ID',false,'sistem','uuid','Ucesnici.id'],['igrac2_id','ID',false,'sistem','uuid','Ucesnici.id'],['izvor1_id','ID',false,'sistem','uuid','Mecevi.id prethodne runde'],['izvor2_id','ID',false,'sistem','uuid','Mecevi.id prethodne runde'],['teren_id','ID',false,'meni','uuid','Tereni.id'],['pocetak','datum-vrijeme',false,'meni','2027-06-10T10:00:00+02:00','ISO sa vremenskom zonom'],['trajanje_min','broj',true,'meni',90,'15–600; procjena'],['status','izbor',true,'meni','Zakazan',['Zakazan','U toku','Završen','Odgođen','Otkazan']],['setovi','tekst',false,'meni','6-4 7-6(7-5)','Setovi orijentisani igrač1–igrač2; taj-brejk oba poena'],['ishod','izbor',false,'meni','Regularno',['Regularno','Predaja','Bez igre','Slobodan prolaz']],['pobjednik_id','ID',false,'sistem','uuid','Jedan od protivnika; automatski prolazak'],['demo','boolean',true,'sistem',false,'DEMO oznaka']],
 Obavjestenja: [
 ['id','ID',true,'sistem','uuid','Stabilan ID'],['naslov','tekst',true,'ručno','','Naslov'],['tekst','tekst',true,'ručno','','Običan tekst; bez HTML-a'],['datum','datum-vrijeme',true,'ručno','','ISO sa vremenskom zonom'],['prioritet','broj',true,'ručno',1,'1 obična, 2 važna, 3 hitna'],['status','izbor',true,'ručno','Nacrt',['Nacrt','Objavljeno']],['demo','boolean',true,'sistem',false,'DEMO oznaka']]
};
SCHEMA.Mecevi.push(['pravila_json','tekst',true,'sistem','{"setovi_za_pobjedu":2,"gemovi_u_setu":6,"tajbrejk_na":6,"tajbrejk_poeni":7}','Snimak pravila prilikom žrijeba; ne mijenjati']);
