const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),crypto=require('node:crypto');
function fixture(){
 let context={},store=new Map([['SPREADSHEET_ID','test-sheet'],['ORGANIZATORI','["owner@example.invalid"]']]),cache=new Map(),locked=false,acquisitions=0,unavailable=false,active=null;
 vm.createContext(context);for(const f of ['Schema.gs','Engine.gs','Demo.gs'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',f),'utf8'),context);
 class Sheet{constructor(values){this.values=values;}getLastRow(){let n=this.values.length;while(n&&this.values[n-1].every(v=>v===''))n--;return n;}getMaxRows(){return 2000;}getDataRange(){return {getValues:()=>this.values.slice(0,this.getLastRow()).map(r=>r.slice())};}clearContents(){this.values=[];}getRange(r,c,n=1,w=1){if(r==='A1'){r=1;c=1;}return {getValue:()=>this.values[r-1]?.[c-1]||'',setValue:v=>{while(this.values.length<r)this.values.push([]);this.values[r-1][c-1]=v;},getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:w},(_,j)=>this.values[r-1+i]?.[c-1+j]??'')),setValues:rows=>{for(let i=0;i<rows.length;i++){while(this.values.length<r+i)this.values.push([]);for(let j=0;j<rows[i].length;j++)this.values[r-1+i][c-1+j]=rows[i][j];}}};}}
 let source=context.Demo.create(Date.now(),crypto.randomUUID),sheets={};for(const [name,cols] of Object.entries(context.SCHEMA)){let headers=cols.map(c=>c[0]);sheets[name]=new Sheet([headers,...source[name].map(r=>headers.map(h=>r[h]??''))]);}sheets._Transakcija=new Sheet([]);
 let ss={getSheetByName:n=>sheets[n],getId:()=> 'test-sheet'};
 Object.assign(context,{PropertiesService:{getScriptProperties:()=>({getProperty:k=>store.get(k),setProperty:(k,v)=>store.set(k,v)})},CacheService:{getScriptCache:()=>({get:k=>{let v=cache.get(k);return v&&v.end>Date.now()?v.value:null;},put:(k,v,t)=>cache.set(k,{value:v,end:Date.now()+t*1000}),remove:k=>cache.delete(k)})},LockService:{getScriptLock:()=>({tryLock:()=>{if(locked)return false;locked=true;acquisitions++;return true;},releaseLock:()=>{locked=false;}})},SpreadsheetApp:{openById:()=>{if(unavailable)throw Error('PRIVATE DATABASE ERROR');return ss;},getActiveSpreadsheet:()=>active,flush:()=>{}},Session:{getActiveUser:()=>({getEmail:()=> 'owner@example.invalid'})},Utilities:{getUuid:crypto.randomUUID,DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(alg,text)=>[...crypto.createHash('sha256').update(text).digest()],newBlob:s=>({getBytes:()=>Buffer.from(s)})}});
 vm.runInContext(fs.readFileSync(path.join(__dirname,'..','Code.gs'),'utf8'),context);
 return {context,cache,ss,sheets,get locked(){return locked},get acquisitions(){return acquisitions},set unavailable(v){unavailable=v},set active(v){active=v}};
}
function request(f){let challenge=f.context.getRegistrationChallenge();f.cache.get('challenge-'+challenge.token).value=String(Date.now()-4000);return {token:challenge.token,zahtjev_id:crypto.randomUUID(),ime_prezime:'DEMO Test',email:'server@example.invalid',telefon:'+38760123456',kategorija_id:'DEMO-C2',klub_grad:'',napomena:'PRIVATE-NOTE',saglasnost:true,verzija_pravila:'DEMO-1'};}
test('real submit handler: persisted row, exact retry idempotency and payload conflict',()=>{let f=fixture(),p=request(f),r=f.context.submitRegistration(p);assert.equal(r.status,'Na čekanju');assert.equal(f.context.read_(f.ss).Prijave.length,7);assert.equal(f.context.submitRegistration(p).id,r.id);assert.equal(f.context.read_(f.ss).Prijave.length,7);assert.throws(()=>f.context.submitRegistration({...p,email:'changed@example.invalid'}),/drugim podacima/);assert.ok(f.acquisitions>=4);assert.equal(f.locked,false);});
test('actual server rejects duplicate, closed, stale challenge and honeypot',()=>{let f=fixture(),p=request(f);f.context.submitRegistration(p);assert.throws(()=>f.context.submitRegistration(request(f)),/već postoji/);let x=fixture(),q=request(x);q.website='bot';assert.throws(()=>x.context.submitRegistration(q),/Provjera/);q.website='';x.cache.delete('challenge-'+q.token);assert.throws(()=>x.context.submitRegistration(q),/Provjera/);let c=fixture();let index=c.context.SCHEMA.Turnir.findIndex(x=>x[0]==='status_prijava');c.sheets.Turnir.values[1][index]='Zatvorene';assert.throws(()=>c.context.submitRegistration(request(c)),/zatvorene/);});
test('getPublicData cache invalidation reflects sheet edit without redeploy',()=>{let f=fixture(),first=f.context.getPublicData();f.sheets.Turnir.values[1][1]='Changed in Sheets';assert.equal(f.context.getPublicData().turnir.naziv,first.turnir.naziv);f.context.edited_({source:f.ss});assert.equal(f.context.getPublicData().turnir.naziv,'Changed in Sheets');});
test('public endpoint no contacts and no internal exception details on outage',()=>{let f=fixture();f.context.submitRegistration(request(f));let s=JSON.stringify(f.context.getPublicData());assert.ok(!s.includes('server@example.invalid'));assert.ok(!s.includes('PRIVATE-NOTE'));f.unavailable=true;assert.throws(()=>f.context.getPublicData(),e=>e.message.includes('nisu dostupni')&&!e.message.includes('PRIVATE'));assert.equal(f.locked,false);});
test('organizer actions reject web context even with owner execution identity',()=>{let f=fixture();assert.throws(()=>f.context.mutate_(['Mecevi'],()=>{}),/ovlašćenje/);f.active=f.ss;assert.doesNotThrow(()=>f.context.mutate_(['Mecevi'],()=>{}));});
test('pending multi-sheet transaction is rolled back before public read',()=>{let f=fixture(),original=f.context.read_(f.ss);f.sheets._Transakcija.values=[['PENDING'],['J'+JSON.stringify({Turnir:original.Turnir})]];f.sheets.Turnir.values[1][1]='PARTIAL WRITE';assert.equal(f.context.getPublicData().turnir.naziv,original.Turnir[0].naziv);assert.equal(f.sheets._Transakcija.values[0][0],'RECOVERED');});
test('quota throttle fails closed and releases lock',()=>{let f=fixture(),p=request(f);f.cache.set('submit-minute-'+Math.floor(Date.now()/60000),{value:'30',end:Date.now()+60000});assert.throws(()=>f.context.submitRegistration(p),/Veliki broj/);assert.equal(f.locked,false);});
test('demo cleanup removes legacy DEMO ids even without the demo flag',()=>{let f=fixture(),demoIndex=f.context.SCHEMA.Tereni.findIndex(c=>c[0]==='demo');f.active=f.ss;f.sheets.Tereni.values[1][demoIndex]=false;f.sheets.Tereni.values[2][demoIndex]=false;f.context.prompt_=()=> 'UKLONI DEMO';f.context.removeDemo_();assert.equal(f.context.read_(f.ss).Tereni.length,0);});
